# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  sirenatravel:
    image: sirenatravel
    build:
      context: .
      dockerfile: ./SirenaTravel/Dockerfile
    ports:
      - 5587:80
    environment:
      - REDIS_CONNECTION=redis://redis-sirenatravel:6379 
      - ProviderOne=http://provider-one
      - ProviderOnePing=api/v1/ping
      - ProviderOneService=api/v1/search
      - ProviderTwo=http://provider-two
      - ProviderTwoPing=api/v1/ping
      - ProviderTwoService=api/v1/search
    networks:
      - sirenatravel
    container_name: sirenatravel
  redis:
    image: redis/redis-stack:latest
    networks:
      - sirenatravel
    ports:
      - 6379:6379
    container_name: redis-sirenatravel
networks:
  sirenatravel:
    driver: bridge
