# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  sirenatravel:
    env_file: .test
    environment:
      - ProviderOne=http://provider-stub:8080
      - ProviderTwo=http://provider-stub:8080
  stub:
    container_name: provider-stub
    image: wiremock/wiremock:latest-alpine
    ports:
      - 8080
    volumes:
        - ./wiremock:/home/wiremock/mappings:ro
    command: --verbose --global-response-templating
    networks:
      - sirenatravel
