# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  sirenatravel:
    image: sirenatravel
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 5587:80
    environment:
     - REDIS_CONNECTION=redis://redis-sirenatravel:6379
    networks:
      - sirenatravel
    container_name: sirenatravel
  redis:
    image: redis/redis-stack:latest
    networks:
      - sirenatravel
    ports:
      - 6379:6379
    container_name: redis-sirenatravel
networks:
  sirenatravel:
    driver: bridge
